development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: today_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: today_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: today_production
  pool: 5